### ISSUE TITLE
As a user, I want to be able to use Azure Open-AI model in LibreChat.

### ISSUE THREAD

**Issue by Endlessflow** [ai-cfia/louis#12]
# Bug Report

## Description

**Bug Summary:**
At the moment Azure Open-AI models are not working in the LibreChat solution.

![Image](https://github.com/ai-cfia/louis/assets/60270865/97876eee-063f-406d-afc1-f569f17f74ee)

**Steps to Reproduce:**

1. Log in to LibreChat.
2. Select Azure Open-AI/gpt-4 model
3. Type a prompt.

**Expected Behavior:**
The model generates an answer.

**Actual Behavior:**
An error message is given to the user prompting them to contact administrators.

## Environment
- **LibreChat Version:** v0.7.2
- **Operating System:** Windows 10
- **Browser (if applicable):** Edge Version 125.0.2535.51 (Official build) (64-bit)

## Logs and Screenshots

**Browser Console Logs:**
![Image](https://github.com/ai-cfia/louis/assets/60270865/aa6558c4-aed4-408b-98b9-925218d8f2e1)

**Container Logs:**
![Image](https://github.com/ai-cfia/louis/assets/60270865/ddb93da2-0e10-4675-8c7a-019d4e2f9e52)

**Comment by SonOfLope** [comment]
Fixed with [current configuration](https://github.com/ai-cfia/howard/blob/d8964d58ad42808b97c5cccc8ee7aaf8fab69b63/kubernetes/aks/apps/librechat/base/librechat-configMap.yaml#L63) in our deployment. We can now generate answers from both model endpoints (gpt4 and gpt-3.5-turbo)
